apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: http-hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: HTTP Hello World Application Project

  # Source repositories that applications in this project can pull manifests from
  sourceRepos:
    - '*'  # Allow all repositories (restrict this in production)

  # Destination clusters and namespaces where applications can be deployed
  destinations:
    - namespace: '*'
      server: '*'

  # Cluster resource whitelist - what can be deployed
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Deny placing resources in certain namespaces
  namespaceResourceBlacklist: []

  # Roles for this project (optional)
  roles:
    - name: admin
      description: Admin privileges for http-hello-world project
      policies:
        - p, proj:http-hello-world:admin, applications, *, http-hello-world/*, allow
      groups:
        - http-hello-world-admins

    - name: developer
      description: Developer privileges for http-hello-world project
      policies:
        - p, proj:http-hello-world:developer, applications, get, http-hello-world/*, allow
        - p, proj:http-hello-world:developer, applications, sync, http-hello-world/*, allow
      groups:
        - http-hello-world-developers
